data_path: '/home/chenzhentao/'
image_path: ''
if_regenerate: False  # 是否重新生成数据
save_path: ''
d: 200  # dimension of the data after applying CSML
pca_dim: 400  # pca降维至几维
ap: 'PCA'  # a0的选择 'WPCA' 'PCA' 'RP' 三种
k: 10  # 验证数据集拆分成多少个子样本
max_repeat: 5000  # 寻找最佳矩阵A时最多循环多少次
